name = "EOEinBLG"
uuid = "9f84cae6-4edd-4b12-bcba-cb6884dbdb14"
authors = ["Fernando Peñaranda"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
